version: '3.7'
services:
  api:
    container_name: covid_api
    env_file: .env
    environment:
      - PORT=$API_PORT
    command: ["/start-reload.sh"]
    build: ./api
    ports:
      - $API_PORT:$API_PORT
    restart: always
    volumes:
      - ./api:/app
    tty: true
  client:
    container_name: covid_client
    env_file: .env
    build: ./client
    ports:
      - $CLIENT_PORT:$CLIENT_PORT
    restart: always
    tty: true
    volumes:
      - ./client:/app
